version: 1.0.{build}
skip_tags: true

environment:
  PYTHON: "C:/Python35"
  SPHINXBUILD: "%PYTHON%/scripts/sphinx-build.exe"

  github_access_token:
    secure: DpN0M7pZDocpyv+muc15qHDKz9lMJ7Zr34aMC0HtOdeVkbTERuKkxq4WHAd3S33v

init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - "%PYTHON%/python.exe -m pip --version"
    - "%PYTHON%/python.exe -m pip install --upgrade pip"

    # Install sphinx (1.5.5) and its extensions
    - "%PYTHON%/python.exe -m pip install sphinx==1.5.5"
    - "%PYTHON%/python.exe -m pip install sphinx-docfx-yaml"
    - "%PYTHON%/python.exe -m pip install sphinx_rtd_theme"
    - "%PYTHON%/python.exe -m pip show sphinx"
    - ps: pip show sphinx-docfx-yaml

clone_script:
    - git config --global core.autocrlf true
    - git config core.autocrlf
    
    # get cntk 2.1 whl file
    - mkdir c:\projects\source
    - ps: (New-Object System.Net.WebClient).DownloadFile("https://cntk.ai/PythonWheel/GPU/cntk-2.1-cp35-cp35m-win_amd64.whl", "c:\projects\source\cntk-2.1-cp35-cp35m-win_amd64.whl")
 
    # get MicrosoftDocs/cognitive-toolkit-docs-python
    - cd c:\projects
    - git clone -q --branch=%PROCESS_REPO_BRANCH% https://github.com/MicrosoftDocs/cognitive-toolkit-docs-python.git

build: off

test: off

on_finish:
    - cd c:\projects\source
    - ps: pip install "c:\projects\source\cntk-2.1-cp35-cp35m-win_amd64.whl"
    - ps: Copy-Item c:/projects/cognitive-toolkit-docs-python/ci_scripts/conf.py -Destination c:/projects/source/conf.py -force
    - ps: Copy-Item c:/projects/cognitive-toolkit-docs-python/ci_scripts/build.bat -Destination c:/projects/source/build.bat -force

    # generate rst files
    - call build.bat
    - "%SPHINXBUILD% . _build"

    # postprocess for toc.yml
    - ps: Copy-Item c:/projects/cognitive-toolkit-docs-python/ci_scripts/postprocess_toc_yml.py -Destination c:/projects/source/postprocess_toc_yml.py -force
    - cd c:\projects\source
    - dir _build\docfx_yaml
    - python postprocess_toc_yml.py

    # remove old yml fils
    - ps: Remove-Item c:\projects\cognitive-toolkit-docs-python\docs-ref-autogen\$env:SOURCE_REPO_VERSION\* -recurse

    # copy yml fils generated
    - ps: Copy-Item -Path C:\projects\source\_build\docfx_yaml\* -Destination c:\projects\cognitive-toolkit-docs-python\docs-ref-autogen\$env:SOURCE_REPO_VERSION\ -recurse -force

    # upload yml to MicrosoftDocs/cognitive-toolkit-docs-python
    - git config --global credential.helper store
    - ps: ac "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
    - cd c:\projects\cognitive-toolkit-docs-python
    - git status
    - git config --global user.name "VSC-Service-Account"
    - git config --global user.email "vscavu@microsoft.com"
    - git add . 
    - git commit -a -m "appveyor ci - update yml files" 
    - git push -u origin %PROCESS_REPO_BRANCH%:%PROCESS_REPO_BRANCH% -f

  
